services:
  scylla:
    image: scylladb/scylla:5.4
    container_name: scylla-godmode
    ports:
      - "9042:9042"
      - "9160:9160"
    volumes:
      - scylla-data:/var/lib/scylla
    command: --smp 2 --memory 2G

  redis:
    image: redis:7-alpine
    container_name: redis-godmode
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redis-ui-godmode
    ports:
      - "5540:5540"
    volumes:
      - redisinsight-data:/data
    environment:
      RI_APP_PORT: 5540
      RI_APP_HOST: 0.0.0.0
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper-godmode
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka-godmode
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-godmode
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - zookeeper
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

volumes:
  scylla-data:
  redis-data:
  redisinsight-data: