// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: socket_server.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerAddress string                 `protobuf:"bytes,1,opt,name=server_address,json=serverAddress,proto3" json:"server_address,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerDetails) Reset() {
	*x = ServerDetails{}
	mi := &file_socket_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerDetails) ProtoMessage() {}

func (x *ServerDetails) ProtoReflect() protoreflect.Message {
	mi := &file_socket_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerDetails.ProtoReflect.Descriptor instead.
func (*ServerDetails) Descriptor() ([]byte, []int) {
	return file_socket_server_proto_rawDescGZIP(), []int{0}
}

func (x *ServerDetails) GetServerAddress() string {
	if x != nil {
		return x.ServerAddress
	}
	return ""
}

func (x *ServerDetails) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type ServerLoad struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerAddress string                 `protobuf:"bytes,1,opt,name=server_address,json=serverAddress,proto3" json:"server_address,omitempty"`
	Load          int32                  `protobuf:"varint,2,opt,name=load,proto3" json:"load,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerLoad) Reset() {
	*x = ServerLoad{}
	mi := &file_socket_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerLoad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerLoad) ProtoMessage() {}

func (x *ServerLoad) ProtoReflect() protoreflect.Message {
	mi := &file_socket_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerLoad.ProtoReflect.Descriptor instead.
func (*ServerLoad) Descriptor() ([]byte, []int) {
	return file_socket_server_proto_rawDescGZIP(), []int{1}
}

func (x *ServerLoad) GetServerAddress() string {
	if x != nil {
		return x.ServerAddress
	}
	return ""
}

func (x *ServerLoad) GetLoad() int32 {
	if x != nil {
		return x.Load
	}
	return 0
}

type GetServerListResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServerList     []*ServerDetails       `protobuf:"bytes,1,rep,name=server_list,json=serverList,proto3" json:"server_list,omitempty"`
	StatusResponse *CommonResponse        `protobuf:"bytes,2,opt,name=status_response,json=statusResponse,proto3" json:"status_response,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetServerListResponse) Reset() {
	*x = GetServerListResponse{}
	mi := &file_socket_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerListResponse) ProtoMessage() {}

func (x *GetServerListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_socket_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerListResponse.ProtoReflect.Descriptor instead.
func (*GetServerListResponse) Descriptor() ([]byte, []int) {
	return file_socket_server_proto_rawDescGZIP(), []int{2}
}

func (x *GetServerListResponse) GetServerList() []*ServerDetails {
	if x != nil {
		return x.ServerList
	}
	return nil
}

func (x *GetServerListResponse) GetStatusResponse() *CommonResponse {
	if x != nil {
		return x.StatusResponse
	}
	return nil
}

type GetServerLoadResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServerLoad     []*ServerLoad          `protobuf:"bytes,1,rep,name=server_load,json=serverLoad,proto3" json:"server_load,omitempty"`
	StatusResponse *CommonResponse        `protobuf:"bytes,2,opt,name=status_response,json=statusResponse,proto3" json:"status_response,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetServerLoadResponse) Reset() {
	*x = GetServerLoadResponse{}
	mi := &file_socket_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerLoadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerLoadResponse) ProtoMessage() {}

func (x *GetServerLoadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_socket_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerLoadResponse.ProtoReflect.Descriptor instead.
func (*GetServerLoadResponse) Descriptor() ([]byte, []int) {
	return file_socket_server_proto_rawDescGZIP(), []int{3}
}

func (x *GetServerLoadResponse) GetServerLoad() []*ServerLoad {
	if x != nil {
		return x.ServerLoad
	}
	return nil
}

func (x *GetServerLoadResponse) GetStatusResponse() *CommonResponse {
	if x != nil {
		return x.StatusResponse
	}
	return nil
}

type SetServerLoadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerLoad    []*ServerLoad          `protobuf:"bytes,1,rep,name=server_load,json=serverLoad,proto3" json:"server_load,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetServerLoadRequest) Reset() {
	*x = SetServerLoadRequest{}
	mi := &file_socket_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetServerLoadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetServerLoadRequest) ProtoMessage() {}

func (x *SetServerLoadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_socket_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetServerLoadRequest.ProtoReflect.Descriptor instead.
func (*SetServerLoadRequest) Descriptor() ([]byte, []int) {
	return file_socket_server_proto_rawDescGZIP(), []int{4}
}

func (x *SetServerLoadRequest) GetServerLoad() []*ServerLoad {
	if x != nil {
		return x.ServerLoad
	}
	return nil
}

var File_socket_server_proto protoreflect.FileDescriptor

const file_socket_server_proto_rawDesc = "" +
	"\n" +
	"\x13socket_server.proto\x12\x05cache\x1a\x15common_response.proto\"S\n" +
	"\rServerDetails\x12%\n" +
	"\x0eserver_address\x18\x01 \x01(\tR\rserverAddress\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\"G\n" +
	"\n" +
	"ServerLoad\x12%\n" +
	"\x0eserver_address\x18\x01 \x01(\tR\rserverAddress\x12\x12\n" +
	"\x04load\x18\x02 \x01(\x05R\x04load\"\x8e\x01\n" +
	"\x15GetServerListResponse\x125\n" +
	"\vserver_list\x18\x01 \x03(\v2\x14.cache.ServerDetailsR\n" +
	"serverList\x12>\n" +
	"\x0fstatus_response\x18\x02 \x01(\v2\x15.cache.CommonResponseR\x0estatusResponse\"\x8b\x01\n" +
	"\x15GetServerLoadResponse\x122\n" +
	"\vserver_load\x18\x01 \x03(\v2\x11.cache.ServerLoadR\n" +
	"serverLoad\x12>\n" +
	"\x0fstatus_response\x18\x02 \x01(\v2\x15.cache.CommonResponseR\x0estatusResponse\"J\n" +
	"\x14SetServerLoadRequest\x122\n" +
	"\vserver_load\x18\x01 \x03(\v2\x11.cache.ServerLoadR\n" +
	"serverLoadB\x03Z\x01.b\x06proto3"

var (
	file_socket_server_proto_rawDescOnce sync.Once
	file_socket_server_proto_rawDescData []byte
)

func file_socket_server_proto_rawDescGZIP() []byte {
	file_socket_server_proto_rawDescOnce.Do(func() {
		file_socket_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_socket_server_proto_rawDesc), len(file_socket_server_proto_rawDesc)))
	})
	return file_socket_server_proto_rawDescData
}

var file_socket_server_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_socket_server_proto_goTypes = []any{
	(*ServerDetails)(nil),         // 0: cache.ServerDetails
	(*ServerLoad)(nil),            // 1: cache.ServerLoad
	(*GetServerListResponse)(nil), // 2: cache.GetServerListResponse
	(*GetServerLoadResponse)(nil), // 3: cache.GetServerLoadResponse
	(*SetServerLoadRequest)(nil),  // 4: cache.SetServerLoadRequest
	(*CommonResponse)(nil),        // 5: cache.CommonResponse
}
var file_socket_server_proto_depIdxs = []int32{
	0, // 0: cache.GetServerListResponse.server_list:type_name -> cache.ServerDetails
	5, // 1: cache.GetServerListResponse.status_response:type_name -> cache.CommonResponse
	1, // 2: cache.GetServerLoadResponse.server_load:type_name -> cache.ServerLoad
	5, // 3: cache.GetServerLoadResponse.status_response:type_name -> cache.CommonResponse
	1, // 4: cache.SetServerLoadRequest.server_load:type_name -> cache.ServerLoad
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_socket_server_proto_init() }
func file_socket_server_proto_init() {
	if File_socket_server_proto != nil {
		return
	}
	file_common_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_socket_server_proto_rawDesc), len(file_socket_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_socket_server_proto_goTypes,
		DependencyIndexes: file_socket_server_proto_depIdxs,
		MessageInfos:      file_socket_server_proto_msgTypes,
	}.Build()
	File_socket_server_proto = out.File
	file_socket_server_proto_goTypes = nil
	file_socket_server_proto_depIdxs = nil
}
