version: '3.8'

services:
  redis-1:
    image: redis
    command: >
      redis-server --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --cluster-node-timeout 5000
                   --appendonly yes
                   --cluster-announce-ip 172.28.0.2
                   --cluster-announce-port 6379
                   --cluster-announce-bus-port 16379
    ports:
      - "6379:6379"
      - "16379:16379"
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.2

  redis-2:
    image: redis
    command: >
      redis-server --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --cluster-node-timeout 5000
                   --appendonly yes
                   --cluster-announce-ip 172.28.0.3
                   --cluster-announce-port 6379
                   --cluster-announce-bus-port 16379
    ports:
      - "6380:6379"
      - "16380:16379"
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.3

  redis-3:
    image: redis
    command: >
      redis-server --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --cluster-node-timeout 5000
                   --appendonly yes
                   --cluster-announce-ip 172.28.0.4
                   --cluster-announce-port 6379
                   --cluster-announce-bus-port 16379
    ports:
      - "6381:6379"
      - "16381:16379"
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.4

  redis-4:
    image: redis
    command: >
      redis-server --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --cluster-node-timeout 5000
                   --appendonly yes
                   --cluster-announce-ip 172.28.0.5
                   --cluster-announce-port 6379
                   --cluster-announce-bus-port 16379
    ports:
      - "6382:6379"
      - "16382:16379"
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.5

  redis-5:
    image: redis
    command: >
      redis-server --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --cluster-node-timeout 5000
                   --appendonly yes
                   --cluster-announce-ip 172.28.0.6
                   --cluster-announce-port 6379
                   --cluster-announce-bus-port 16379
    ports:
      - "6383:6379"
      - "16383:16379"
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.6

  redis-6:
    image: redis
    command: >
      redis-server --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --cluster-node-timeout 5000
                   --appendonly yes
                   --cluster-announce-ip 172.28.0.7
                   --cluster-announce-port 6379
                   --cluster-announce-bus-port 16379
    ports:
      - "6384:6379"
      - "16384:16379"
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.7

networks:
  redis-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
