// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: chat.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	ChatName      string                 `protobuf:"bytes,2,opt,name=chat_name,json=chatName,proto3" json:"chat_name,omitempty"`
	ChatType      string                 `protobuf:"bytes,3,opt,name=chat_type,json=chatType,proto3" json:"chat_type,omitempty"` // e.g., "group", "private"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatDetails) Reset() {
	*x = ChatDetails{}
	mi := &file_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatDetails) ProtoMessage() {}

func (x *ChatDetails) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatDetails.ProtoReflect.Descriptor instead.
func (*ChatDetails) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ChatDetails) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ChatDetails) GetChatName() string {
	if x != nil {
		return x.ChatName
	}
	return ""
}

func (x *ChatDetails) GetChatType() string {
	if x != nil {
		return x.ChatType
	}
	return ""
}

type UsersByChatIdResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserList       []*UserDetails         `protobuf:"bytes,1,rep,name=user_list,json=userList,proto3" json:"user_list,omitempty"`
	StatusResponse *CommonResponse        `protobuf:"bytes,2,opt,name=status_response,json=statusResponse,proto3" json:"status_response,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UsersByChatIdResponse) Reset() {
	*x = UsersByChatIdResponse{}
	mi := &file_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersByChatIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersByChatIdResponse) ProtoMessage() {}

func (x *UsersByChatIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersByChatIdResponse.ProtoReflect.Descriptor instead.
func (*UsersByChatIdResponse) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{1}
}

func (x *UsersByChatIdResponse) GetUserList() []*UserDetails {
	if x != nil {
		return x.UserList
	}
	return nil
}

func (x *UsersByChatIdResponse) GetStatusResponse() *CommonResponse {
	if x != nil {
		return x.StatusResponse
	}
	return nil
}

type UserToChat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chat          *ChatDetails           `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	User          *UserDetails           `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserToChat) Reset() {
	*x = UserToChat{}
	mi := &file_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserToChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserToChat) ProtoMessage() {}

func (x *UserToChat) ProtoReflect() protoreflect.Message {
	mi := &file_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserToChat.ProtoReflect.Descriptor instead.
func (*UserToChat) Descriptor() ([]byte, []int) {
	return file_chat_proto_rawDescGZIP(), []int{2}
}

func (x *UserToChat) GetChat() *ChatDetails {
	if x != nil {
		return x.Chat
	}
	return nil
}

func (x *UserToChat) GetUser() *UserDetails {
	if x != nil {
		return x.User
	}
	return nil
}

var File_chat_proto protoreflect.FileDescriptor

const file_chat_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"chat.proto\x12\x05cache\x1a\x15common_response.proto\x1a\n" +
	"user.proto\"`\n" +
	"\vChatDetails\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x1b\n" +
	"\tchat_name\x18\x02 \x01(\tR\bchatName\x12\x1b\n" +
	"\tchat_type\x18\x03 \x01(\tR\bchatType\"\x88\x01\n" +
	"\x15UsersByChatIdResponse\x12/\n" +
	"\tuser_list\x18\x01 \x03(\v2\x12.cache.UserDetailsR\buserList\x12>\n" +
	"\x0fstatus_response\x18\x02 \x01(\v2\x15.cache.CommonResponseR\x0estatusResponse\"\\\n" +
	"\n" +
	"UserToChat\x12&\n" +
	"\x04chat\x18\x01 \x01(\v2\x12.cache.ChatDetailsR\x04chat\x12&\n" +
	"\x04user\x18\x02 \x01(\v2\x12.cache.UserDetailsR\x04userB\x03Z\x01.b\x06proto3"

var (
	file_chat_proto_rawDescOnce sync.Once
	file_chat_proto_rawDescData []byte
)

func file_chat_proto_rawDescGZIP() []byte {
	file_chat_proto_rawDescOnce.Do(func() {
		file_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)))
	})
	return file_chat_proto_rawDescData
}

var file_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_chat_proto_goTypes = []any{
	(*ChatDetails)(nil),           // 0: cache.ChatDetails
	(*UsersByChatIdResponse)(nil), // 1: cache.UsersByChatIdResponse
	(*UserToChat)(nil),            // 2: cache.UserToChat
	(*UserDetails)(nil),           // 3: cache.UserDetails
	(*CommonResponse)(nil),        // 4: cache.CommonResponse
}
var file_chat_proto_depIdxs = []int32{
	3, // 0: cache.UsersByChatIdResponse.user_list:type_name -> cache.UserDetails
	4, // 1: cache.UsersByChatIdResponse.status_response:type_name -> cache.CommonResponse
	0, // 2: cache.UserToChat.chat:type_name -> cache.ChatDetails
	3, // 3: cache.UserToChat.user:type_name -> cache.UserDetails
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_chat_proto_init() }
func file_chat_proto_init() {
	if File_chat_proto != nil {
		return
	}
	file_common_response_proto_init()
	file_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_proto_rawDesc), len(file_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chat_proto_goTypes,
		DependencyIndexes: file_chat_proto_depIdxs,
		MessageInfos:      file_chat_proto_msgTypes,
	}.Build()
	File_chat_proto = out.File
	file_chat_proto_goTypes = nil
	file_chat_proto_depIdxs = nil
}
