// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: poke_user.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageDetails struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageContent string                 `protobuf:"bytes,1,opt,name=message_content,json=messageContent,proto3" json:"message_content,omitempty"`
	ToUserId       string                 `protobuf:"bytes,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	FromUserId     string                 `protobuf:"bytes,3,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	SentAt         string                 `protobuf:"bytes,4,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	ChatId         string                 `protobuf:"bytes,5,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageDetails) Reset() {
	*x = MessageDetails{}
	mi := &file_poke_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDetails) ProtoMessage() {}

func (x *MessageDetails) ProtoReflect() protoreflect.Message {
	mi := &file_poke_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDetails.ProtoReflect.Descriptor instead.
func (*MessageDetails) Descriptor() ([]byte, []int) {
	return file_poke_user_proto_rawDescGZIP(), []int{0}
}

func (x *MessageDetails) GetMessageContent() string {
	if x != nil {
		return x.MessageContent
	}
	return ""
}

func (x *MessageDetails) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *MessageDetails) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *MessageDetails) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

func (x *MessageDetails) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

var File_poke_user_proto protoreflect.FileDescriptor

const file_poke_user_proto_rawDesc = "" +
	"\n" +
	"\x0fpoke_user.proto\x12\x05cache\"\xab\x01\n" +
	"\x0eMessageDetails\x12'\n" +
	"\x0fmessage_content\x18\x01 \x01(\tR\x0emessageContent\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\tR\btoUserId\x12 \n" +
	"\ffrom_user_id\x18\x03 \x01(\tR\n" +
	"fromUserId\x12\x17\n" +
	"\asent_at\x18\x04 \x01(\tR\x06sentAt\x12\x17\n" +
	"\achat_id\x18\x05 \x01(\tR\x06chatIdB\x03Z\x01.b\x06proto3"

var (
	file_poke_user_proto_rawDescOnce sync.Once
	file_poke_user_proto_rawDescData []byte
)

func file_poke_user_proto_rawDescGZIP() []byte {
	file_poke_user_proto_rawDescOnce.Do(func() {
		file_poke_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_poke_user_proto_rawDesc), len(file_poke_user_proto_rawDesc)))
	})
	return file_poke_user_proto_rawDescData
}

var file_poke_user_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_poke_user_proto_goTypes = []any{
	(*MessageDetails)(nil), // 0: cache.MessageDetails
}
var file_poke_user_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_poke_user_proto_init() }
func file_poke_user_proto_init() {
	if File_poke_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_poke_user_proto_rawDesc), len(file_poke_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_poke_user_proto_goTypes,
		DependencyIndexes: file_poke_user_proto_depIdxs,
		MessageInfos:      file_poke_user_proto_msgTypes,
	}.Build()
	File_poke_user_proto = out.File
	file_poke_user_proto_goTypes = nil
	file_poke_user_proto_depIdxs = nil
}
