// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: socket_service.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SocketService_PokeUser_FullMethodName = "/cache.SocketService/PokeUser"
)

// SocketServiceClient is the client API for SocketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SocketServiceClient interface {
	PokeUser(ctx context.Context, in *MessageDetails, opts ...grpc.CallOption) (*CommonResponse, error)
}

type socketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSocketServiceClient(cc grpc.ClientConnInterface) SocketServiceClient {
	return &socketServiceClient{cc}
}

func (c *socketServiceClient) PokeUser(ctx context.Context, in *MessageDetails, opts ...grpc.CallOption) (*CommonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommonResponse)
	err := c.cc.Invoke(ctx, SocketService_PokeUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SocketServiceServer is the server API for SocketService service.
// All implementations must embed UnimplementedSocketServiceServer
// for forward compatibility.
type SocketServiceServer interface {
	PokeUser(context.Context, *MessageDetails) (*CommonResponse, error)
	mustEmbedUnimplementedSocketServiceServer()
}

// UnimplementedSocketServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSocketServiceServer struct{}

func (UnimplementedSocketServiceServer) PokeUser(context.Context, *MessageDetails) (*CommonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PokeUser not implemented")
}
func (UnimplementedSocketServiceServer) mustEmbedUnimplementedSocketServiceServer() {}
func (UnimplementedSocketServiceServer) testEmbeddedByValue()                       {}

// UnsafeSocketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SocketServiceServer will
// result in compilation errors.
type UnsafeSocketServiceServer interface {
	mustEmbedUnimplementedSocketServiceServer()
}

func RegisterSocketServiceServer(s grpc.ServiceRegistrar, srv SocketServiceServer) {
	// If the following call pancis, it indicates UnimplementedSocketServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SocketService_ServiceDesc, srv)
}

func _SocketService_PokeUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocketServiceServer).PokeUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocketService_PokeUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocketServiceServer).PokeUser(ctx, req.(*MessageDetails))
	}
	return interceptor(ctx, in, info, handler)
}

// SocketService_ServiceDesc is the grpc.ServiceDesc for SocketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SocketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cache.SocketService",
	HandlerType: (*SocketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PokeUser",
			Handler:    _SocketService_PokeUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "socket_service.proto",
}
