// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: socket_server.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerAddress string `protobuf:"bytes,1,opt,name=server_address,json=serverAddress,proto3" json:"server_address,omitempty"`
	ServerId      string `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
}

func (x *ServerDetails) Reset() {
	*x = ServerDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_socket_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerDetails) ProtoMessage() {}

func (x *ServerDetails) ProtoReflect() protoreflect.Message {
	mi := &file_socket_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerDetails.ProtoReflect.Descriptor instead.
func (*ServerDetails) Descriptor() ([]byte, []int) {
	return file_socket_server_proto_rawDescGZIP(), []int{0}
}

func (x *ServerDetails) GetServerAddress() string {
	if x != nil {
		return x.ServerAddress
	}
	return ""
}

func (x *ServerDetails) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type ServerLoad struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerAddress string `protobuf:"bytes,1,opt,name=server_address,json=serverAddress,proto3" json:"server_address,omitempty"`
	Load          int32  `protobuf:"varint,2,opt,name=load,proto3" json:"load,omitempty"`
}

func (x *ServerLoad) Reset() {
	*x = ServerLoad{}
	if protoimpl.UnsafeEnabled {
		mi := &file_socket_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerLoad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerLoad) ProtoMessage() {}

func (x *ServerLoad) ProtoReflect() protoreflect.Message {
	mi := &file_socket_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerLoad.ProtoReflect.Descriptor instead.
func (*ServerLoad) Descriptor() ([]byte, []int) {
	return file_socket_server_proto_rawDescGZIP(), []int{1}
}

func (x *ServerLoad) GetServerAddress() string {
	if x != nil {
		return x.ServerAddress
	}
	return ""
}

func (x *ServerLoad) GetLoad() int32 {
	if x != nil {
		return x.Load
	}
	return 0
}

type GetServerListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerList     []*ServerDetails `protobuf:"bytes,1,rep,name=server_list,json=serverList,proto3" json:"server_list,omitempty"`
	StatusResponse *CommonResponse  `protobuf:"bytes,2,opt,name=status_response,json=statusResponse,proto3" json:"status_response,omitempty"`
}

func (x *GetServerListResponse) Reset() {
	*x = GetServerListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_socket_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServerListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerListResponse) ProtoMessage() {}

func (x *GetServerListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_socket_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerListResponse.ProtoReflect.Descriptor instead.
func (*GetServerListResponse) Descriptor() ([]byte, []int) {
	return file_socket_server_proto_rawDescGZIP(), []int{2}
}

func (x *GetServerListResponse) GetServerList() []*ServerDetails {
	if x != nil {
		return x.ServerList
	}
	return nil
}

func (x *GetServerListResponse) GetStatusResponse() *CommonResponse {
	if x != nil {
		return x.StatusResponse
	}
	return nil
}

type GetServerLoadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerLoad     []*ServerLoad   `protobuf:"bytes,1,rep,name=server_load,json=serverLoad,proto3" json:"server_load,omitempty"`
	StatusResponse *CommonResponse `protobuf:"bytes,2,opt,name=status_response,json=statusResponse,proto3" json:"status_response,omitempty"`
}

func (x *GetServerLoadResponse) Reset() {
	*x = GetServerLoadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_socket_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServerLoadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerLoadResponse) ProtoMessage() {}

func (x *GetServerLoadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_socket_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerLoadResponse.ProtoReflect.Descriptor instead.
func (*GetServerLoadResponse) Descriptor() ([]byte, []int) {
	return file_socket_server_proto_rawDescGZIP(), []int{3}
}

func (x *GetServerLoadResponse) GetServerLoad() []*ServerLoad {
	if x != nil {
		return x.ServerLoad
	}
	return nil
}

func (x *GetServerLoadResponse) GetStatusResponse() *CommonResponse {
	if x != nil {
		return x.StatusResponse
	}
	return nil
}

var File_socket_server_proto protoreflect.FileDescriptor

var file_socket_server_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63, 0x61, 0x63, 0x68, 0x65, 0x1a, 0x15, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x53, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x4c, 0x6f, 0x61, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6c, 0x6f, 0x61,
	0x64, 0x22, 0x8e, 0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0b, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x3e, 0x0a, 0x0f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x61,
	0x63, 0x68, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x52, 0x0e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x8b, 0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x4c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x0b,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x4c, 0x6f, 0x61, 0x64, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4c, 0x6f, 0x61, 0x64,
	0x12, 0x3e, 0x0a, 0x0f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x61, 0x63, 0x68,
	0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x0e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_socket_server_proto_rawDescOnce sync.Once
	file_socket_server_proto_rawDescData = file_socket_server_proto_rawDesc
)

func file_socket_server_proto_rawDescGZIP() []byte {
	file_socket_server_proto_rawDescOnce.Do(func() {
		file_socket_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_socket_server_proto_rawDescData)
	})
	return file_socket_server_proto_rawDescData
}

var file_socket_server_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_socket_server_proto_goTypes = []any{
	(*ServerDetails)(nil),         // 0: cache.ServerDetails
	(*ServerLoad)(nil),            // 1: cache.ServerLoad
	(*GetServerListResponse)(nil), // 2: cache.GetServerListResponse
	(*GetServerLoadResponse)(nil), // 3: cache.GetServerLoadResponse
	(*CommonResponse)(nil),        // 4: cache.CommonResponse
}
var file_socket_server_proto_depIdxs = []int32{
	0, // 0: cache.GetServerListResponse.server_list:type_name -> cache.ServerDetails
	4, // 1: cache.GetServerListResponse.status_response:type_name -> cache.CommonResponse
	1, // 2: cache.GetServerLoadResponse.server_load:type_name -> cache.ServerLoad
	4, // 3: cache.GetServerLoadResponse.status_response:type_name -> cache.CommonResponse
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_socket_server_proto_init() }
func file_socket_server_proto_init() {
	if File_socket_server_proto != nil {
		return
	}
	file_common_response_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_socket_server_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ServerDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_socket_server_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ServerLoad); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_socket_server_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetServerListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_socket_server_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetServerLoadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_socket_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_socket_server_proto_goTypes,
		DependencyIndexes: file_socket_server_proto_depIdxs,
		MessageInfos:      file_socket_server_proto_msgTypes,
	}.Build()
	File_socket_server_proto = out.File
	file_socket_server_proto_rawDesc = nil
	file_socket_server_proto_goTypes = nil
	file_socket_server_proto_depIdxs = nil
}
